const pdfcreation = require("./travel_quote_pdf");

const travelPolicyExample = {
  id: 1,
  name: "Europe,Africa,MiddleEast",
  description: "",
  type: "individual",
  currency: "KES",
  medicalExpenses: 130000,
  medicalRepatriation: 20000,
  childRepatriation: 4000,
  relativesRepatriation: 4000,
  bodyRepatriation: 10000,
  opticalEmergencyCare: 400,
  dentalEmergencyCare: 400,
  followUpTreatment: 600,
  prematureReturnInCaseOfDeath: 4000,
  advanceOfBail: 6000,
  legalAssistance: 1500,
  lossOrTheftUnregisteredLuggage: 1500,
  lossOrTheftRegisteredLuggage: 600,
  luggageDelay: 400,
  travelDelay: 400,
  personalCivilLiability: null,
  hijackInMeansOfPublicTransport: null,
  journeyCancelation: null,
  journeyCurtailment: null,
  missedTravelConnection: null,
  schengenCountries: true,
  schengenCountriesRate: 175,
  winterSports: true,
  winterSportsRate: 100,
  maxAge: 75,
  minAge: 0,
  UnderwriterId: 1,
  user: {
    id: 13,
    firstName: "John",
    lastName: "Doe",
    phoneNumber: "0713805244",
    email: "allanbmageto2@yopmail.com",
    tempPassword: false,
    isVerified: true,
    UserCategoryId: 1,
    UserCategory: {
      id: 1,
      name: "Client",
      description: null,
      createdAt: "2020-02-27T05:32:03.000Z",
      updatedAt: "2020-02-27T05:32:03.000Z",
    },
    iat: 1586691181,
    exp: 1586734381,
  },
};

const policyPdfDirectory = "./documentsStorage/PolicyPdf/output.pdf";

pdfcreation.createInvoice(travelPolicyExample, policyPdfDirectory);
